# Generated by Django 3.2 on 2022-10-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_logo', models.ImageField(upload_to='images')),
                ('admin_mail', models.CharField(max_length=100)),
            ],
        ),
    ]
